
services:
  - type: web
    name: viperpro-laravel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      cp .env.example .env
      php artisan key:generate
      npm install
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan serve --host=0.0.0.0 --port=$PORT
